"""
Step 3-2: Update SQL Queries with Ambiguous Values

After Step 3-1 modifies the database with synonym values, the original SQL
queries are no longer correct (the exact-match WHERE conditions fail). This
script updates the SQL queries by replacing equality conditions (=) with IN
clauses that include all synonym values present in the modified database.

Transformations:
  - `column = 'value'`  -->  `column IN ('value', 'synonym1', 'synonym2', ...)`
  - `column != 'value'` -->  `column NOT IN ('value', 'synonym1', ...)`

The list of synonym values used in each IN clause is taken from the
replacement mapping generated by Step 3-1 (update2sqlite_*.json), ensuring
the SQL query matches exactly what was inserted into the database.

Input:
  - Merged question JSON from Step 2-3
  - Replacement value mapping from Step 3-1

Output:
  - Updated JSON with "query_amb" field containing the modified SQL
    (e.g., all_dev_gpt-4o_reformat_question_merge_newsql.json)
"""

import json
from sqlglot import parse_one, exp


def replace_condition(node, value, value_synonym, column):
    """
    Transform an AST node: replace EQ/NEQ on the target column+value
    with an IN/NOT IN clause using all synonym values.
    """
    if (
            (isinstance(node, exp.EQ) or isinstance(node, exp.NEQ)) and
            isinstance(node.this, exp.Column) and
            node.this.name.lower() == column.lower() and
            (
                    (
                            isinstance(node.expression, exp.Literal) and
                            node.expression.this == value
                    )
                    or (
                            not isinstance(node.expression, exp.Literal) and
                            node.expression.this.name.lower() == value.lower()
                    )
            )
    ):
        new_expressions = [exp.Literal.string(synonym) for synonym in value_synonym]
        column_name_gt = node.this.name
        table_name_gt = node.this.table

        if isinstance(node, exp.NEQ):
            new_condition = exp.Not(
                this=exp.In(
                    this=exp.Column(this=column_name_gt, table=table_name_gt),
                    expressions=new_expressions
                )
            )
        else:
            new_condition = exp.In(
                this=exp.Column(this=column_name_gt, table=table_name_gt),
                expressions=new_expressions
            )
        print("New Condition:", new_condition)
        return new_condition

    return node


if __name__ == '__main__':
    type_str = "dev"
    model_llm_api = "gpt-4o"

    file_name = f"all_{type_str}_{model_llm_api}_reformat_question_merge.json"
    output_path = f"all_{type_str}_{model_llm_api}_reformat_question_merge_newsql.json"
    file_replace_value_path = f"update2sqlite_{type_str}_{model_llm_api}.json"

    with open(file_name) as inf:
        data_reformat_dict = json.load(inf)
    with open(file_replace_value_path) as inf:
        replace_value_dict = json.load(inf)

    for db_id in data_reformat_dict:
        if "db_schema" not in data_reformat_dict[db_id]:
            continue

        for question_text in data_reformat_dict[db_id]["question_dict_merge"]:
            question_item_0 = data_reformat_dict[db_id]["question_dict_merge"][question_text][0]
            sql_query = question_item_0["query"]

            try:
                tree = parse_one(sql_query, read='mysql')
            except Exception as e:
                print("Error:", e)

            for question_item in data_reformat_dict[db_id]["question_dict_merge"][question_text]:
                value = question_item["value"]
                table = question_item["table"]
                column = question_item["column"]
                value_in_db = value

                # Handle special cases for specific databases with padding
                if db_id == "flight_2" and table == "flights" and (
                        column == "destairport" or column == "sourceairport"):
                    if value not in sql_query:
                        value = " " + value
                    value_in_db = " " + value

                if db_id == "flight_2" and table == "airports" and column == "city":
                    if value not in sql_query:
                        value = value + " "
                    value_in_db = value + " "

                if db_id == "california_schools" and table == "schools" and column == "virtual" and value == "F (Virtual)":
                    if value not in sql_query:
                        value = "F"
                    value_in_db = "F"

                # Build the full synonym list from the replacement mapping
                value_synonym = [value_in_db]
                if value_in_db in replace_value_dict[db_id][table][column]:
                    value_synonym.extend(replace_value_dict[db_id][table][column][value_in_db])
                if value_in_db.lower() in replace_value_dict[db_id][table][column]:
                    value_synonym.extend(replace_value_dict[db_id][table][column][value_in_db.lower()])
                    value_synonym.append(value_in_db.lower())

                # Hardcoded fix for "Chinese" value
                if value_in_db == "Chinese":
                    value_synonym.extend(["Chinese", 'Mandarin Chinese', 'Chinese tongue', 'Chinese dialect', 'Canton Chinese'])

                # Update data_synonym to match what was actually inserted into the database
                data_reformat_dict[db_id][table][column]['data_synonym'][value] = value_synonym

                # Skip if no synonyms were added (no change to SQL needed)
                if [value_in_db] == value_synonym:
                    continue

                value_synonym = list(set(value_synonym))

                # Transform the SQL AST: replace = with IN clause
                tree = tree.transform(
                    lambda node: replace_condition(node, value, value_synonym, column))

            # Store the modified SQL query for all question items
            for question_item in data_reformat_dict[db_id]["question_dict_merge"][question_text]:
                question_item["query_amb"] = tree.sql()

    json.dump(data_reformat_dict, open(output_path, 'w'), indent=2, separators=(",", ": "))
